// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package queries

import (
	"database/sql"
)

type User struct {
	ID        int64
	Name      sql.NullString
	Phone     sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
